// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtA_UDtyIyfPcjJhUAyQRvIMw54ar1e4',
    appId: '1:547370214775:web:dc48c648c3c0ef96a36d72',
    messagingSenderId: '547370214775',
    projectId: 'wayk-app',
    authDomain: 'wayk-app.firebaseapp.com',
    storageBucket: 'wayk-app.firebasestorage.app',
    measurementId: 'G-B2KZQRGW2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCstemqncfCXyo7co9e-iX94As3w6rvYA8',
    appId: '1:547370214775:android:053320964a841eb8a36d72',
    messagingSenderId: '547370214775',
    projectId: 'wayk-app',
    storageBucket: 'wayk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUDBn_acHK4trPMumLhv9ewIAWRN8VcQ',
    appId: '1:547370214775:ios:958cd784f737eb27a36d72',
    messagingSenderId: '547370214775',
    projectId: 'wayk-app',
    storageBucket: 'wayk-app.firebasestorage.app',
    iosBundleId: 'com.example.waykFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUDBn_acHK4trPMumLhv9ewIAWRN8VcQ',
    appId: '1:547370214775:ios:958cd784f737eb27a36d72',
    messagingSenderId: '547370214775',
    projectId: 'wayk-app',
    storageBucket: 'wayk-app.firebasestorage.app',
    iosBundleId: 'com.example.waykFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbtA_UDtyIyfPcjJhUAyQRvIMw54ar1e4',
    appId: '1:547370214775:web:6649c8dc7258b20da36d72',
    messagingSenderId: '547370214775',
    projectId: 'wayk-app',
    authDomain: 'wayk-app.firebaseapp.com',
    storageBucket: 'wayk-app.firebasestorage.app',
    measurementId: 'G-SN8SQB1Z0X',
  );
}
